# Generated by Django 4.1.4 on 2023-01-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_current_education_details_eighth_sem_sgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
