# Generated by Django 4.1.4 on 2023-01-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_other_details_profile_backlogs_profile_other_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_edu_details',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='past_edu_details',
        ),
        migrations.AddField(
            model_name='current_education_details',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_details',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='past_education_details',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
