# Generated by Django 4.1.4 on 2023-01-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_company_job_profile_placed_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_companies',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.job_profile'),
        ),
    ]
