# Generated by Django 4.1.4 on 2023-01-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_alter_registered_companies_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_students',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='registered_companies',
            name='profile',
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.CharField(default='Software engineering', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='job_profile',
        ),
    ]
