# Generated by Django 4.1.4 on 2023-01-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_remove_placed_students_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobProfile', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
        ),
        migrations.AddField(
            model_name='placed_students',
            name='JobProfile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='placement.jobprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registered_companies',
            name='JobProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.jobprofile'),
        ),
    ]
