# Generated by Django 4.1.4 on 2023-01-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_jobprofile_placed_students_jobprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_students',
            name='JobProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.jobprofile'),
        ),
    ]
