# Generated by Django 4.1.4 on 2023-01-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_alter_placed_students_jobprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile',
        ),
    ]
