# Generated by Django 4.1.4 on 2023-01-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_remove_company_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='placed_students',
            name='JobProfile',
        ),
        migrations.RemoveField(
            model_name='registered_companies',
            name='JobProfile',
        ),
        migrations.DeleteModel(
            name='JobProfile',
        ),
        migrations.AddField(
            model_name='placed_students',
            name='job_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.job_profile'),
        ),
        migrations.AddField(
            model_name='registered_companies',
            name='job_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.job_profile'),
        ),
    ]
