# Generated by Django 4.0.6 on 2023-01-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_job_profile_remove_placed_students_jobprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.company'),
        ),
    ]
